# -*- coding: utf-8 -*-
"""sales_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cgxRWwjyexce3ma9OhvOdEaLAJvpG5PO
"""

import pandas as pd
import numpy as np

def load_data(filepath):
    """Load dataset from a CSV file."""
    return pd.read_csv("datset - Sheet1.csv")

def clean_data(df):
    """Remove rows with missing/null values."""
    return df.dropna()

def sum_sales_by_region(df):
    """Calculate the sum of sales by region."""
    return df.groupby('Region')['TotalSales'].sum()

def avg_sales_per_product(df):
    """Calculate the average sales per product."""
    return df.groupby('Product')['TotalSales'].mean()

def best_and_worst_selling_products(df):
    """Find highest and lowest selling products."""
    product_sales = df.groupby('Product')['TotalSales'].sum()
    return product_sales.idxmax(), product_sales.idxmin()

def calculate_statistics(df):
    """Use NumPy to calculate mean, median, and standard deviation of sales."""
    sales = df['TotalSales'].values
    return {
        'mean': np.mean(sales),
        'median': np.median(sales),
        'std_dev': np.std(sales)
    }

def main():
    filepath = 'sales_data.csv'
    df = load_data(filepath)
    df = clean_data(df)

    print("=== Sales by Region ===")
    print(sum_sales_by_region(df))

    print("\n=== Average Sales per Product ===")
    print(avg_sales_per_product(df))

    high, low = best_and_worst_selling_products(df)
    print(f"\nHighest Selling Product: {high}")
    print(f"Lowest Selling Product: {low}")

    stats = calculate_statistics(df)
    print("\n=== Sales Statistics ===")
    print(f"Mean: {stats['mean']:.2f}")
    print(f"Median: {stats['median']:.2f}")
    print(f"Standard Deviation: {stats['std_dev']:.2f}")

if __name__ == "__main__":
    main()